name: my_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.9.0
  firebase_auth: ^5.3.4
  camera: ^0.10.0
  tflite: ^1.1.2
  image_picker: ^0.8.7+4
  audioplayers: ^6.1.0
  cloud_firestore: ^5.0.1



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - images/avatar.png
    - images/logo.jpg
    - images/magical_background.png
    - assets/sounds/music.mp3
    - images/dragon.jpg
  fonts:
    - family: Irish Grover
      fonts:
        - asset: assets/fonts/IrishGrover-Regular.ttf
